[package]
name = "blinky"
version = "0.1.0"
edition = "2024"

[features]
default = ["esp32c6"]

esp32c6 = [
    #"esp-backtrace/esp32c6",
    #"esp-println/esp32c6",
    "esp-bootloader-esp-idf/esp32c6",
    "esp-rtos/esp32c6",
    "esp-hal/esp32c6",
]

[dependencies]
defmt                   = { version = "1" }

critical-section        = "1.2"

embassy-time            = {  version = "0.5.1",  features = ["defmt"] }
embassy-executor        = { version = "0.10.0", features = ["defmt"] }

esp-bootloader-esp-idf  = { version = "0.5.0",      features = ["defmt"] }
esp-hal                 = { version = "1.1.1", features = ["defmt", "unstable"] }
esp-rtos                = { version = "0.3.0", features = ["embassy", "defmt"] }

rtt-target       = { version = "0.6.2", features = ["defmt"] }
#esp-backtrace           = { version = "0.19.0",           features = ["defmt", "panic-handler"], optional = true }
#esp-println             = { version = "0.17.0", features = ["defmt-espflash", "jtag-serial"], default-features = false }
